### ISSUE TITLE
UnmarshalBinaryBare cannot decode empty bytes when checking account detail

### ISSUE THREAD

**Issue by shenzhun** [cosmos/testnets#20] opened 2018-05-14 09:16 UTC
gaiad version: 0.16.0-dev-7ef5e90
os: Ubuntu(4.4.0-1055-aws)
go version: 1.10

````
~$ gaiacli account CDB6DE2C96D3AE85A47BEF453ADF089152BA8F79
panic: UnmarshalBinaryBare cannot decode empty bytes

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/auth/client/cli.GetAccountDecoder.func1(0x0, 0x0, 0x0, 0x1, 0xc63fd2, 0x15, 0x0)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/x/auth/client/cli/account.go:25 +0xd7
github.com/cosmos/cosmos-sdk/x/auth/client/cli.GetAccountCmd.func1(0xc420207400, 0xc420069e50, 0x1, 0x1, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/x/auth/client/cli/account.go:56 +0x1a6
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc420207400, 0xc420069e20, 0x1, 0x1, 0xc420207400, 0xc420069e20)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:756 +0x468
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x124a2c0, 0xc727c6, 0x24, 0xc420034c7f)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0x124a2c0, 0xc420114f00, 0x124a3b0)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:794 +0x2b
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x124a2c0, 0xdb2f18, 0x2, 0xc4209b8260)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/cli/setup.go:89 +0x4e
main.main()
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/cmd/gaia/cmd/gaiacli/main.go:75 +0x4a6

**Comment by cwgoes** [comment] 2018-05-14 09:39
Thanks for reporting this. Duplicate of https://github.com/cosmos/cosmos-sdk/issues/930 - we'll track it on the SDK repository. This error is confusing; it just means that the account is unknown (no balance).

**Closed by cwgoes** 2018-05-14 09:39 UTC
