### ISSUE TITLE
Imported key is not visible before it sends a tx

### ISSUE THREAD

**Issue by gbunea** [cosmos/testnets#124] opened 2019-01-27 20:14 UTC
I imported a key using --recover flag. If I tried to see the key details before sending any tx by using query command and I received the following error message:

"ERROR: decoding bech32 failed: checksum failed. Expected n5tvq0, got 9h4fk3.
[root@I044 ~]# gaiacli query account cosmos1d7s4n059rze09859enym6zjqvxcdqcqw9h4fk3  --chain-id=gaia-10k
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xadd41f]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/auth.BaseAccount.String(0xc000b9b740, 0x14, 0x14, 0xc000a3fa40, 0x2, 0x2, 0x0, 0x0, 0x3bb, 0x0, ...)
	/root/gaia/src/github.com/cosmos/cosmos-sdk/x/auth/account.go:91 +0x3f
github.com/cosmos/cosmos-sdk/client/context.CLIContext.PrintOutput(0xc00013b1f0, 0xc000aab6b0, 0x13630e0, 0xc000b2a620, 0x134caa0, 0xc00000e018, 0xebe708, 0x4, 0x0, 0xece2e8, ...)
	/root/gaia/src/github.com/cosmos/cosmos-sdk/client/context/context.go:266 +0x253
github.com/cosmos/cosmos-sdk/x/auth/client/cli.GetAccountCmd.func1(0xc0001a8f00, 0xc000a75620, 0x1, 0x2, 0x0, 0x0)
	/root/gaia/src/github.com/cosmos/cosmos-sdk/x/auth/client/cli/account.go:38 +0x320
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001a8f00, 0xc000a755e0, 0x2, 0x2, 0xc0001a8f00, 0xc000a755e0)
	/root/gaia/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d9680, 0x24, 0xc00090f9f8, 0xed6e6b)
	/root/gaia/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000d9680, 0x1, 0xc0001d48c0)
	/root/gaia/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000d9680, 0x12827e0, 0x2, 0xc00090e220)
	/root/gaia/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
	/root/gaia/src/github.com/cosmos/cosmos-sdk/cmd/gaia/cmd/gaiacli/main.go:102 +0x58c"

After a tx is sent, the details of the key can be correctly seen using query command.

**Comment by alexanderbez** [comment] 2019-01-28 14:34
Thanks @gbunea this is a duplicate of https://github.com/cosmos/cosmos-sdk/issues/3401.

**Closed by alexanderbez** 2019-01-28 14:34 UTC
